/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "auth.login": [],
    "auth.sign.in": [],
    "auth.forgot.password": [],
    "auth.forgot.send.password": [],
    "auth.register": [],
    "auth.sign.up": [],
    "auth.logout": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "admin.home": [],
    "admin.dashboard": [],
    "admin.offers": [],
    "admin.offers.create": [],
    "admin.offers.store": [],
    "admin.offers.edit": [
        {
            "name": "offer",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.offers.update": [
        {
            "name": "offer",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
